spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/k15?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    ##初始连接数，默认0
    initialSize: 10
    #最大连接数，默认8
    maxActive: 30
    #最小闲置数
    minIdle: 10
    #获取连接的最大等待时间，单位毫秒
    maxWait: 2000
    #缓存PreparedStatement，默认false
    poolPreparedStatements: true
    #缓存PreparedStatement的最大数量，默认-1（不缓存）。大于0时会自动开启缓存PreparedStatement，所以可以省略上一句设置
    maxOpenPreparedStatements: 20
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    jackson:
      date-format: yyyy-MM-dd
  thymeleaf:
    cache: false
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} ----- [%thread] %-5level %logger{50} - %msg%n'
  level:
    com.example.vuedserver: debug   # 只要是在这个包 （com.woniu.boot05） 日志的输出级别都是 debug
